/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.agendatelefonica.vista.menu;

import com.agendatelefonica.Agenda;
import com.agendatelefonica.vista.DataCompartida;
import com.agendatelefonica.vista.agregar.Agregar;
import com.agendatelefonica.vista.buscarexistencia.Buscar;
import com.agendatelefonica.vista.eliminar.Eliminar;
import com.agendatelefonica.vista.modificar.Modificar;
import com.agendatelefonica.vista.mostrartelefono.BuscarMuestra;

import javax.swing.*;

/**
 *
 * @author migue
 */
public class Menu extends javax.swing.JFrame {
    private DataCompartida datos = new DataCompartida();
    /**
     * Creates new form Menu
     */
    public Menu(DataCompartida datos) {
        initComponents();
        this.datos.setAgenda(datos.getAgenda());
        contenedorInfo.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        menuOpciones = new javax.swing.JComboBox<>();
        contenedorInfo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Menu principal");

        menuOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Añadir contacto", "Buscar existencia de contacto", "Listar contactos", "Buscar contacto", "Eliminar contacto", "Modificar teléfono", "Mostrar si la agenda está llena", "Mostrar los espacios libres de la agenda" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(menuOpciones, 0, 169, Short.MAX_VALUE)
                .addGap(59, 59, 59)
                .addComponent(jButton1)
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(contenedorInfo)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(menuOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(contenedorInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int desicion = menuOpciones.getSelectedIndex();
        System.out.println(datos.getAgenda().getTamanoMax());
        contenedorInfo.setText("");
        switch (desicion){
            case 0:
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new Agregar(datos).setVisible(true);
                    }
                });
                break;
            case 1:
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new Buscar(datos).setVisible(true);
                    }
                });
                break;
            case 2:
                contenedorInfo.setText(datos.getAgenda().toString());
                break;
            case 3:
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new BuscarMuestra(datos).setVisible(true);
                    }
                });
                break;
            case 4:
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new Eliminar(datos).setVisible(true);
                    }
                });
                break;
            case 5:
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new Modificar(datos).setVisible(true);
                    }
                });
                break;
            case 6:
                boolean lleno = datos.getAgenda().agendaLlena();
                if(lleno){
                    JOptionPane.showMessageDialog(this, "No cuenta con espacio en su agenda", "Información", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Aun cuenta con espacio en su agenda", "Información", JOptionPane.INFORMATION_MESSAGE);
                }
                break;
            case 7:
                int espacio = datos.getAgenda().espacioLibres();
                if(espacio >=1){
                    JOptionPane.showMessageDialog(this, "El espacio en su agenda es: " + espacio, "Información", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "No cuenta con espacio en su agenda", "Información", JOptionPane.INFORMATION_MESSAGE);
                }
                break;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contenedorInfo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private static javax.swing.JComboBox<String> menuOpciones;
    // End of variables declaration//GEN-END:variables
}
